modLoader="javafml"
loaderVersion="[36,)"
license="Not specified"

[[mods]]
modId="minecraft_eragon_fraktions"
version="1.0.2"
displayName="Minecraft Eragon fraktions"
credits="Created using mod maker MCreator - https://mcreator.net/about and Eclipse  https://www.eclipse.org/ "
displayURL="https://mcreator.net"
authors="KATLA66"

[[dependencies.minecraft_eragon_fraktions]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"




